
export const BOOK_CODE_TO_NAME: Record<string, string> = {
  '1CH': '1 Chronicles',
  '1CO': '1 Corinthians',
  '1ES': 'Esdras I',
  '1JN': '1 John',
  '1KI': '1 Kings',
  '1MA': 'I Maccabees',
  '1PE': '1 Peter',
  '1SA': '1 Samuel',
  '1TH': '1 Thessalonians',
  '1TI': '1 Timothy',
  '2CH': '2 Chronicles',
  '2CO': '2 Corinthians',
  '2ES': '2 Esdras',
  '2JN': '2 John',
  '2KI': '2 Kings',
  '2MA': 'II Maccabees',
  '2PE': '2 Peter',
  '2SA': '2 Samuel',
  '2TH': '2 Thessalonians',
  '2TI': '2 Timothy',
  '3JN': '3 John',
  '3MA': 'III Maccabees',
  '4MA': 'IV Maccabees',
  'ACT': 'Acts',
  'AMO': 'Amos',
  'BAR': 'Baruch',
  'BEL': 'Bel and the Dragon',
  'COL': 'Colossians',
  'DAG': 'Daniel (Greek)',
  'DAN': 'Daniel',
  'DEU': 'Deuteronomy',
  'ECC': 'Ecclesiastes',
  'EPH': 'Ephesians',
  'ESG': 'Esther (Greek)',
  'EST': 'Esther',
  'EXO': 'Exodus',
  'EZK': 'Ezekiel',
  'EZR': 'Ezra',
  'GAL': 'Galatians',
  'GEN': 'Genesis',
  'HAB': 'Habakkuk',
  'HAG': 'Haggai',
  'HEB': 'Hebrews',
  'HOS': 'Hosea',
  'ISA': 'Isaiah',
  'JAS': 'James',
  'JDG': 'Judges',
  'JDT': 'Judith',
  'JER': 'Jeremiah',
  'JHN': 'John',
  'JOB': 'Job',
  'JOL': 'Joel',
  'JON': 'Jonah',
  'JOS': 'Joshua',
  'JUD': 'Jude',
  'LAM': 'Lamentations',
  'LEV': 'Leviticus',
  'LJE': 'Epistle of Jeremiah',
  'LUK': 'Luke',
  'MAL': 'Malachi',
  'MAN': 'Prayer of Manasses',
  'MAT': 'Matthew',
  'MIC': 'Micah',
  'MRK': 'Mark',
  'NAM': 'Nahum',
  'NEH': 'Nehemiah',
  'NUM': 'Numbers',
  'OBA': 'Obadiah',
  'PHM': 'Philemon',
  'PHP': 'Philippians',
  'PRO': 'Proverbs',
  'PS2': 'Psalm 151',
  'PSA': 'Psalms',
  'REV': 'Revelation',
  'ROM': 'Romans',
  'RUT': 'Ruth',
  'S3Y': 'Song of the Three Holy Children',
  'SIR': 'Sirach',
  'SNG': 'Song of Solomon',
  'SUS': 'Susanna',
  'TIT': 'Titus',
  'TOB': 'Tobit',
  'WIS': 'Wisdom',
  'ZEC': 'Zechariah',
  'ZEP': 'Zephaniah',
};