import { Platform, StyleSheet } from 'react-native';
import { theme } from '../../theme';

const cardBackground = '#fffef9';

export const authFormStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.primary,
  },
  scrollGrow: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing.lg,
  },
  card: {
    width: '100%',
    maxWidth: 400,
    minHeight: 500,
    backgroundColor: cardBackground,
    borderRadius: theme.radius.sm,
    paddingHorizontal: 40,
    paddingVertical: 50,
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: theme.colors.foreground,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
      },
      android: { elevation: 8 },
    }),
  },
  wrapper: { width: '100%', alignItems: 'center' },
  logo: { height: 55, width: 180, marginBottom: theme.spacing.lg },
  title: {
    fontSize: theme.typography.sizes.xl,
    fontWeight: theme.typography.weights.regular,
    color: theme.colors.foreground,
    textAlign: 'center',
    marginBottom: theme.spacing.sm,
  },
  subtitle: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.mutedForeground,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: theme.spacing.xl,
  },
  fieldContainer: {
    width: '100%',
    marginBottom: theme.spacing.lg,
    position: 'relative',
  },
  floatingLabel: {
    position: 'absolute',
    top: -8,
    left: 10,
    backgroundColor: cardBackground,
    paddingHorizontal: 4,
    fontSize: theme.typography.sizes.xs,
    fontWeight: theme.typography.weights.semibold,
    color: theme.colors.primary,
    zIndex: 2,
  },
  floatingLabelError: { color: theme.colors.destructive },
  input: {
    width: '100%',
    height: 48,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.sm,
    paddingHorizontal: theme.spacing.md,
    fontSize: theme.typography.sizes.md,
    color: theme.colors.foreground,
    backgroundColor: theme.colors.background,
  },
  passwordWrapper: {
    width: '100%',
    position: 'relative',
    flexDirection: 'row',
  },
  passwordInput: {
    flex: 1,
    height: 48,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.sm,
    paddingLeft: theme.spacing.md,
    paddingRight: 45,
    fontSize: theme.typography.sizes.md,
    color: theme.colors.foreground,
    backgroundColor: theme.colors.background,
  },
  passwordToggle: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputErrorBorder: {
    borderColor: theme.colors.destructive,
    borderWidth: 1.5,
    backgroundColor: theme.colors.background,
  },
  errorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
    paddingHorizontal: 2,
  },
  errorText: {
    color: theme.colors.destructive,
    fontSize: 13,
    flex: 1,
  },
  linkButton: { alignSelf: 'flex-start', marginBottom: theme.spacing.lg },
  subSecondaryLink: {
    marginTop: theme.spacing.md,
    width: '100%',
    alignItems: 'center',
  },
  linkText: {
    color: theme.colors.primary,
    fontSize: theme.typography.sizes.sm,
    fontWeight: theme.typography.weights.medium,
  },
  primaryButton: {
    backgroundColor: theme.colors.primary,
    width: '100%',
    height: 48,
    borderRadius: theme.radius.sm,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryButtonDisabled: { opacity: 0.6 },
  primaryButtonText: {
    color: theme.colors.primaryForeground,
    fontSize: theme.typography.sizes.md,
    fontWeight: theme.typography.weights.semibold,
  },
  successIconCircle: {
    width: 74,
    height: 74,
    borderRadius: 37,
    borderWidth: 2,
    borderColor: theme.colors.syncSynced,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: theme.spacing.lg,
  },
  boldTargetText: {
    fontWeight: theme.typography.weights.semibold,
    color: theme.colors.foreground,
  },
  secondaryButton: {
    width: '100%',
    height: 48,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.background,
    borderRadius: theme.radius.sm,
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: theme.colors.foreground,
    fontSize: theme.typography.sizes.md,
    fontWeight: theme.typography.weights.semibold,
  },
  footer: {
    marginTop: 30,
    width: '100%',
    paddingTop: theme.spacing.sm,
  },
  footerText: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.mutedForeground,
    textAlign: 'center',
    lineHeight: 16,
  },
  footerLink: { color: theme.colors.primary },
});
